version: '3.8'
services:
  db:
    image: "mysql:8.0"
    container_name: "Mysql-v8"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_ROOT_PASSWORD: secret4570
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

#comand Run
#docker-compose -f docker-compose-mysql-only.yml up